# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [4]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))
print(np.exp(5.2))

-1.0
1.1
5.2
181.27224187515122


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [7]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


NameError: name 'arange' is not defined

In [9]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(2,5)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556 1.11111111 1.66666667 2.22222222]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [10]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [12]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [13]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [14]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [28]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.937172   0.52754241 0.35378866 0.6116586  0.99663353]
 [0.70403515 0.4486373  0.89436526 0.93639234 0.52788372]
 [0.64106924 0.97255271 0.7923532  0.10185905 0.57740723]
 [0.7141032  0.13022538 0.51487126 0.10829607 0.32575445]
 [0.97216856 0.73343015 0.37266523 0.42957596 0.45616331]]

[[ 0.25840922 -1.33482262  0.39309528  0.45275526  0.72463263]
 [-1.50510618 -1.06632586 -0.50563516  0.03715047  0.24968016]
 [-0.72128021 -1.3620836  -0.84808899  0.20249221 -0.17763174]
 [-0.0054247   2.13948102  0.39155735  0.32330081 -2.21231306]
 [-0.53450173  0.27440638 -1.90063844 -0.40554865 -0.0118721 ]
 [ 1.58454835  0.87317605  0.49857094 -1.65388074 -0.30293862]
 [-0.74294524  0.10851894  0.85886188 -0.46307289  0.79244052]
 [ 0.67720213  1.440043   -0.83665944 -0.98411111 -0.72072809]
 [ 1.11540021 -1.23144366 -1.98552287  2.40735742  0.84654984]
 [ 0.8519322  -1.20559847 -0.71041728 -1.13422872 -1.09009395]]


In [16]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.44775293933212623
1.0439429347071059


In [17]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.004257331433277778
2.1787289207679446


In [ ]:
# break here for next video!

In [18]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.3766728   0.72797077 -1.38407048  1.40520249  0.78685981  1.7994454
 -1.47872589 -0.3189637  -0.61528934  1.23562116  0.0082352   0.78695785
  0.25036205  0.45093851 -2.16200056  0.55872057 -0.79446294  0.56712187
 -0.36474572]
-1.4787258943476218


In [19]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.78685981  1.7994454  -1.47872589 -0.3189637  -0.61528934]


In [20]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.3766728   1.40520249 -1.47872589  1.23562116  0.25036205]


In [21]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.13912307 0.70994485 0.03923237 0.83306136 0.763506  ]
 [0.0673896  0.67922923 0.4318535  0.86309714 0.57908782]
 [0.68855911 0.22500603 0.07663345 0.87848501 0.51387786]
 [0.90232287 0.17711671 0.00425733 0.31911998 0.04200126]
 [0.93047475 0.34501368 0.0295465  0.11471294 0.84117107]]
0.4318534984540262
0.4318534984540262


In [22]:
print(rand_mat[0:2,1:3])

[[0.70994485 0.03923237]
 [0.67922923 0.4318535 ]]


In [23]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.3766728   0.72797077 -1.38407048  1.40520249  0.78685981  1.7994454
 -1.47872589 -0.3189637  -0.61528934  1.23562116  0.0082352   0.78695785
  0.25036205  0.45093851 -2.16200056  0.55872057 -0.79446294  0.56712187
 -0.36474572]

[ 0.3766728   0.72797077 -1.38407048  4.          4.          1.7994454
 -1.47872589 -0.3189637  -0.61528934  1.23562116  0.0082352   0.78695785
  0.25036205  0.45093851 -2.16200056  0.55872057 -0.79446294  0.56712187
 -0.36474572]

[ 0.3766728   0.72797077 -1.38407048  1.          2.          1.7994454
 -1.47872589 -0.3189637  -0.61528934  1.23562116  0.0082352   0.78695785
  0.25036205  0.45093851 -2.16200056  0.55872057 -0.79446294  0.56712187
 -0.36474572]


In [35]:
print(rand_mat)
rand_mat[2:3,3:5] =4
print('')
print(rand_mat)

[[0.937172   0.52754241 0.35378866 0.6116586  0.99663353]
 [0.70403515 2.         3.         3.         8.        ]
 [0.64106924 0.97255271 0.7923532  4.         0.57740723]
 [0.7141032  0.13022538 0.51487126 0.10829607 0.32575445]
 [0.97216856 0.73343015 0.37266523 0.42957596 0.45616331]]

[[0.937172   0.52754241 0.35378866 0.6116586  0.99663353]
 [0.70403515 2.         3.         3.         8.        ]
 [0.64106924 0.97255271 0.7923532  4.         4.        ]
 [0.7141032  0.13022538 0.51487126 0.10829607 0.32575445]
 [0.97216856 0.73343015 0.37266523 0.42957596 0.45616331]]


In [37]:
print(rand_mat)
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.937172   0.52754241 0.35378866 0.6116586  0.99663353]
 [0.70403515 2.         3.         3.         8.        ]
 [0.64106924 0.97255271 0.7923532  4.         4.        ]
 [0.7141032  0.13022538 0.51487126 0.10829607 0.32575445]
 [0.97216856 0.73343015 0.37266523 0.42957596 0.45616331]]
[[0.937172   0.52754241 0.35378866]
 [0.70403515 2.         3.        ]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [38]:
print(rand_mat)

[[3.         3.         3.         0.6116586  0.99663353]
 [3.         3.         3.         3.         8.        ]
 [0.64106924 0.97255271 0.7923532  4.         4.        ]
 [0.7141032  0.13022538 0.51487126 0.10829607 0.32575445]
 [0.97216856 0.73343015 0.37266523 0.42957596 0.45616331]]


In [39]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.6116586  0.99663353]
 [3.         3.         3.         3.         8.        ]
 [0.64106924 0.97255271 0.7923532  4.         4.        ]
 [0.7141032  0.13022538 0.51487126 0.10829607 0.32575445]
 [0.97216856 0.73343015 0.37266523 0.42957596 0.45616331]]


In [ ]:
# break here for next video

In [40]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.38910037  1.28212547 -0.08448536 -0.19252755  2.08885882 -0.04724377
 -0.26077497 -2.73909605 -1.04892259 -0.42206176  0.02356823 -0.59240248
  0.47050358 -0.22499543  1.72907981]
[False  True False False  True False False False False False  True False
  True False  True]
[1.28212547 2.08885882 0.02356823 0.47050358 1.72907981]


In [41]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.25840922 -1.33482262  0.39309528  0.45275526  0.72463263]
 [-1.50510618 -1.06632586 -0.50563516  0.03715047  0.24968016]
 [-0.72128021 -1.3620836  -0.84808899  0.20249221 -0.17763174]
 [-0.0054247   2.13948102  0.39155735  0.32330081 -2.21231306]
 [-0.53450173  0.27440638 -1.90063844 -0.40554865 -0.0118721 ]
 [ 1.58454835  0.87317605  0.49857094 -1.65388074 -0.30293862]
 [-0.74294524  0.10851894  0.85886188 -0.46307289  0.79244052]
 [ 0.67720213  1.440043   -0.83665944 -0.98411111 -0.72072809]
 [ 1.11540021 -1.23144366 -1.98552287  2.40735742  0.84654984]
 [ 0.8519322  -1.20559847 -0.71041728 -1.13422872 -1.09009395]]
[0.25840922 0.39309528 0.45275526 0.72463263 0.03715047 0.24968016
 0.20249221 2.13948102 0.39155735 0.32330081 0.27440638 1.58454835
 0.87317605 0.49857094 0.10851894 0.85886188 0.79244052 0.67720213
 1.440043   1.11540021 2.40735742 0.84654984 0.8519322 ]


In [ ]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

In [ ]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [ ]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [ ]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)